-- Daily Paths: collapse 132 secondary themes to 43.
-- Generated 2026-09-30 from editorial/theme-taxonomy-readings.csv
-- Run in the Supabase SQL editor. Everything is inside one transaction:
-- if any statement fails, nothing is applied.
--
-- Rollback for the readings column is in editorial/theme-taxonomy-rollback.sql

BEGIN;

-- 1. Guard: stop if the table is not the shape this script was written against.
DO $$ BEGIN
  IF (SELECT count(*) FROM readings) <> 366 THEN
    RAISE EXCEPTION 'Expected 366 readings, found %', (SELECT count(*) FROM readings);
  END IF;
END $$;

-- 2. Retag the readings. 280 of 366 rows change; the other 86 already
--    carry the theme they should have, and are left out rather than rewritten.
UPDATE readings AS r SET secondary_theme = v.theme
FROM (VALUES
  (2, 'Honesty'),
  (3, 'Powerlessness'),
  (4, 'Understanding the Disease'),
  (5, 'Understanding the Disease'),
  (6, 'Self-Focus'),
  (7, 'Letting Go'),
  (8, 'Powerlessness'),
  (10, 'Understanding the Disease'),
  (12, 'Hope and Gratitude'),
  (13, 'Powerlessness'),
  (14, 'Acceptance'),
  (16, 'Letting Go'),
  (17, 'Self-Care'),
  (18, 'Letting Go'),
  (19, 'Detachment'),
  (20, 'People-Pleasing'),
  (21, 'Self-Focus'),
  (24, 'Boundaries'),
  (25, 'Self-Awareness'),
  (26, 'Practice'),
  (27, 'Self-Worth'),
  (28, 'Resentment and Forgiveness'),
  (29, 'Responsibility'),
  (30, 'Practice'),
  (32, 'Hope and Gratitude'),
  (33, 'Coming to Believe'),
  (34, 'Hope and Gratitude'),
  (35, 'Coming to Believe'),
  (36, 'Coming to Believe'),
  (37, 'Fellowship'),
  (38, 'Self-Awareness'),
  (41, 'Hope and Gratitude'),
  (43, 'Letting Go'),
  (45, 'Spiritual Growth'),
  (46, 'Coming to Believe'),
  (48, 'Fellowship'),
  (49, 'Trusting Others'),
  (53, 'Prayer and Meditation'),
  (55, 'Open-Mindedness'),
  (56, 'Responsibility'),
  (57, 'Respect'),
  (58, 'Humility'),
  (60, 'Serenity'),
  (61, 'Self-Awareness'),
  (62, 'Willingness'),
  (63, 'Surrender'),
  (64, 'Surrender'),
  (65, 'Letting Go'),
  (67, 'Coming to Believe'),
  (68, 'Letting Go'),
  (69, 'Letting Go'),
  (71, 'Letting Go'),
  (72, 'Fear'),
  (73, 'Surrender'),
  (74, 'Coming to Believe'),
  (75, 'Coming to Believe'),
  (76, 'Coming to Believe'),
  (77, 'Respect'),
  (78, 'Self-Compassion'),
  (79, 'Courage'),
  (80, 'Surrender'),
  (82, 'Faith'),
  (84, 'Coming to Believe'),
  (86, 'Coming to Believe'),
  (87, 'Fellowship'),
  (89, 'Trusting Others'),
  (91, 'Trusting Others'),
  (92, 'Inventory'),
  (93, 'Inventory'),
  (95, 'Progress Not Perfection'),
  (96, 'Hope and Gratitude'),
  (97, 'Responsibility'),
  (99, 'Identity'),
  (102, 'Identity'),
  (103, 'Self-Worth'),
  (106, 'People-Pleasing'),
  (107, 'Self-Awareness'),
  (109, 'Honesty'),
  (110, 'Self-Compassion'),
  (111, 'Inventory'),
  (112, 'Courage'),
  (113, 'Self-Focus'),
  (114, 'People-Pleasing'),
  (115, 'Progress Not Perfection'),
  (116, 'Hope and Gratitude'),
  (117, 'Practice'),
  (118, 'Honesty'),
  (119, 'Self-Awareness'),
  (120, 'Self-Awareness'),
  (121, 'Spiritual Growth'),
  (122, 'Shame and Guilt'),
  (123, 'People-Pleasing'),
  (125, 'Shame and Guilt'),
  (126, 'Responsibility'),
  (129, 'Trusting Others'),
  (130, 'Fellowship'),
  (131, 'Courage'),
  (133, 'Character Defects'),
  (134, 'Shame and Guilt'),
  (136, 'Honesty'),
  (137, 'Self-Awareness'),
  (138, 'Connection'),
  (139, 'Connection'),
  (140, 'Shame and Guilt'),
  (141, 'Honesty'),
  (142, 'Fellowship'),
  (145, 'Shame and Guilt'),
  (146, 'Shame and Guilt'),
  (147, 'Self-Focus'),
  (148, 'Understanding the Disease'),
  (149, 'Understanding the Disease'),
  (150, 'Fellowship'),
  (151, 'Open-Mindedness'),
  (152, 'Service'),
  (153, 'Readiness'),
  (154, 'Readiness'),
  (156, 'Readiness'),
  (157, 'Readiness'),
  (158, 'Character Defects'),
  (159, 'Character Defects'),
  (160, 'Character Defects'),
  (161, 'Prayer and Meditation'),
  (163, 'Trust in a Higher Power'),
  (164, 'Readiness'),
  (165, 'Character Defects'),
  (167, 'Letting Go'),
  (168, 'Surrender'),
  (169, 'Readiness'),
  (171, 'Prayer and Meditation'),
  (173, 'Acceptance'),
  (177, 'Surrender'),
  (181, 'Responsibility'),
  (182, 'Humility'),
  (183, 'Humility'),
  (186, 'Self-Worth'),
  (187, 'Humility'),
  (188, 'Letting Go'),
  (189, 'Patience'),
  (190, 'Prayer and Meditation'),
  (191, 'Letting Go'),
  (193, 'Progress Not Perfection'),
  (194, 'Self-Compassion'),
  (195, 'Self-Compassion'),
  (196, 'Practice'),
  (197, 'Self-Awareness'),
  (198, 'Practice'),
  (199, 'Serenity'),
  (200, 'Self-Awareness'),
  (201, 'Spiritual Growth'),
  (202, 'Character Defects'),
  (203, 'Self-Awareness'),
  (205, 'Trust in a Higher Power'),
  (206, 'Progress Not Perfection'),
  (207, 'Practice'),
  (209, 'Self-Worth'),
  (210, 'Boundaries'),
  (212, 'Connection'),
  (213, 'Practice'),
  (214, 'Shame and Guilt'),
  (216, 'Inventory'),
  (217, 'Resentment and Forgiveness'),
  (218, 'Responsibility'),
  (219, 'Willingness'),
  (220, 'Willingness'),
  (221, 'Prayer and Meditation'),
  (222, 'Letting Go'),
  (223, 'Amends'),
  (224, 'Amends'),
  (225, 'Acceptance'),
  (226, 'Amends'),
  (228, 'Prayer and Meditation'),
  (229, 'Responsibility'),
  (230, 'Acceptance'),
  (231, 'Self-Focus'),
  (232, 'Patience'),
  (233, 'Amends'),
  (234, 'Amends'),
  (235, 'Amends'),
  (236, 'Resentment and Forgiveness'),
  (238, 'Trust in a Higher Power'),
  (239, 'Amends'),
  (240, 'Respect'),
  (242, 'Fellowship'),
  (243, 'Trusting Others'),
  (244, 'Trusting Others'),
  (246, 'Responsibility'),
  (247, 'Amends'),
  (248, 'Amends'),
  (249, 'Amends'),
  (250, 'Living Amends'),
  (251, 'Living Amends'),
  (252, 'Acceptance'),
  (253, 'Amends'),
  (254, 'Living Amends'),
  (255, 'Fear'),
  (256, 'Fellowship'),
  (258, 'Resentment and Forgiveness'),
  (259, 'Living Amends'),
  (260, 'Living Amends'),
  (261, 'Amends'),
  (262, 'Living Amends'),
  (263, 'Amends'),
  (264, 'Living Amends'),
  (266, 'Character Defects'),
  (268, 'Service'),
  (269, 'Service'),
  (271, 'Living Amends'),
  (272, 'Acceptance'),
  (273, 'Amends'),
  (274, 'Living Amends'),
  (275, 'Practice'),
  (277, 'Practice'),
  (278, 'Inventory'),
  (279, 'Progress Not Perfection'),
  (280, 'Practice'),
  (281, 'Self-Awareness'),
  (282, 'Responsibility'),
  (283, 'Self-Awareness'),
  (284, 'Serenity'),
  (285, 'Inventory'),
  (287, 'Resentment and Forgiveness'),
  (288, 'Letting Go'),
  (290, 'Self-Worth'),
  (291, 'Character Defects'),
  (292, 'Acceptance'),
  (293, 'Progress Not Perfection'),
  (294, 'Self-Care'),
  (295, 'Responsibility'),
  (296, 'Resentment and Forgiveness'),
  (297, 'Practice'),
  (299, 'Inventory'),
  (300, 'Readiness'),
  (302, 'Fellowship'),
  (303, 'Fellowship'),
  (304, 'Trusting Others'),
  (305, 'Progress Not Perfection'),
  (306, 'Trust in a Higher Power'),
  (307, 'Prayer and Meditation'),
  (308, 'Prayer and Meditation'),
  (310, 'Practice'),
  (311, 'Prayer and Meditation'),
  (313, 'Prayer and Meditation'),
  (317, 'Self-Awareness'),
  (318, 'Faith'),
  (320, 'Letting Go'),
  (322, 'Open-Mindedness'),
  (324, 'Prayer and Meditation'),
  (326, 'Self-Compassion'),
  (327, 'Serenity'),
  (328, 'Self-Compassion'),
  (330, 'Progress Not Perfection'),
  (331, 'Self-Compassion'),
  (333, 'Spiritual Growth'),
  (334, 'Hope and Gratitude'),
  (336, 'Practice'),
  (337, 'Spiritual Growth'),
  (339, 'Spiritual Growth'),
  (340, 'Spiritual Growth'),
  (341, 'Detachment'),
  (343, 'Service'),
  (344, 'Fellowship'),
  (347, 'Living Amends'),
  (348, 'Practice'),
  (349, 'Acceptance'),
  (350, 'Practice'),
  (351, 'Spiritual Growth'),
  (352, 'Trust in a Higher Power'),
  (353, 'Self-Worth'),
  (354, 'Resentment and Forgiveness'),
  (355, 'Letting Go'),
  (357, 'Letting Go'),
  (358, 'Self-Awareness'),
  (359, 'Open-Mindedness'),
  (360, 'Hope and Gratitude'),
  (361, 'Open-Mindedness'),
  (362, 'Fear'),
  (363, 'Open-Mindedness'),
  (364, 'Open-Mindedness'),
  (365, 'Open-Mindedness'),
  (366, 'People-Pleasing')
) AS v(day, theme)
WHERE r.day_of_year = v.day;

-- 3. Rebuild the destination table. It is keyed by theme NAME, so once the names
--    change every old row is orphaned. Each new theme inherits the destination that
--    most of its readings already resolve to today, so Go deeper keeps working.
DELETE FROM reflection_theme_destinations;
INSERT INTO reflection_theme_destinations (theme, destination) VALUES
  ('Acceptance', '/guides/surrender/'),
  ('Amends', '/guides/detachment-with-love/'),
  ('Boundaries', '/guides/boundaries/'),
  ('Character Defects', '/topics/self-worth/'),
  ('Coming to Believe', '/topics/higher-power/'),
  ('Connection', '/topics/fellowship/'),
  ('Courage', '/articles/letting-go/'),
  ('Detachment', '/guides/detachment-with-love/'),
  ('Faith', '/topics/higher-power/'),
  ('Fear', '/guides/surrender/'),
  ('Fellowship', '/topics/fellowship/'),
  ('Honesty', '/articles/the-stories-we-tell-ourselves/'),
  ('Hope and Gratitude', '/topics/gratitude-and-hope/'),
  ('Humility', '/guides/surrender/'),
  ('Identity', '/topics/self-worth/'),
  ('Inventory', '/articles/the-stories-we-tell-ourselves/'),
  ('Letting Go', '/guides/surrender/'),
  ('Living Amends', '/articles/the-stories-we-tell-ourselves/'),
  ('Open-Mindedness', '/topics/fellowship/'),
  ('Patience', '/topics/one-day-at-a-time/'),
  ('People-Pleasing', '/guides/boundaries/'),
  ('Powerlessness', '/guides/surrender/'),
  ('Practice', '/traditions/'),
  ('Prayer and Meditation', '/topics/higher-power/'),
  ('Progress Not Perfection', '/articles/the-stories-we-tell-ourselves/'),
  ('Readiness', '/guides/surrender/'),
  ('Resentment and Forgiveness', '/guides/surrender/'),
  ('Respect', '/guides/boundaries/'),
  ('Responsibility', '/articles/the-stories-we-tell-ourselves/'),
  ('Self-Awareness', '/articles/the-stories-we-tell-ourselves/'),
  ('Self-Care', '/topics/focus-on-yourself/'),
  ('Self-Compassion', '/topics/self-worth/'),
  ('Self-Focus', '/topics/focus-on-yourself/'),
  ('Self-Worth', '/topics/self-worth/'),
  ('Serenity', '/topics/one-day-at-a-time/'),
  ('Service', '/topics/gratitude-and-hope/'),
  ('Shame and Guilt', '/guides/surrender/'),
  ('Spiritual Growth', '/topics/higher-power/'),
  ('Surrender', '/guides/surrender/'),
  ('Trust in a Higher Power', '/topics/higher-power/'),
  ('Trusting Others', '/topics/higher-power/'),
  ('Understanding the Disease', '/topics/the-disease/'),
  ('Willingness', '/articles/letting-go/');

-- 4. Verify before committing.
SELECT count(DISTINCT secondary_theme) AS themes_now FROM readings;  -- expect 43
SELECT count(*) AS destination_rows FROM reflection_theme_destinations;  -- expect 43
SELECT secondary_theme, count(*) FROM readings GROUP BY 1 HAVING count(*) < 5;  -- expect 0 rows

-- Replace with ROLLBACK; if any check above looks wrong.
COMMIT;
